language: c

os:
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - liblua5.2-dev
      - libssl-dev
      - liblzo2-dev

before_install:
  - if [ "$CC" = "gcc" ]; then sudo apt-get install gcc-4.9 && export CC="gcc-4.9"; fi

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
